security:
    # Провайдеры пользователей
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    # Настройки хэширования паролей
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Firewall
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
                target: app_login

    # Права доступа
    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }